version: "3.9"

services:
  web:
    image: nginx:alpine
    ports:
      - "8080:80"
    volumes:
      - ./awesome-fonts:/usr/share/nginx/html:ro
    deploy:
      restart_policy:
        condition: any

networks:
  webnet:
    driver: overlay
